---
sidebar: sidebar 
permalink: ontap98fo_netapp_ontap.html 
keywords: TR-4872, 4872, introduction, NAS, SAN, NFS, SMB, S3, HA 
summary: Esta página apresenta uma visão geral dos recursos mais recentes do ONTAP 9.8 e links para mais informações. 
---
= TR-4872: Visão geral do recurso do NetApp ONTAP 9.8
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Justin Parisi, NetApp

O NetApp ONTAP é o principal software de gerenciamento de dados da NetApp, líder do setor, que permite que você gerencie e proteja seus dados de forma otimizada onde quer que estejam, seja no local, na borda ou na nuvem.

O NetApp ONTAP oferece suporte para os seguintes recursos, todos na mesma plataforma:

* Protocolos nas (NFS e SMB)
* Protocolos SAN (iSCSI, FCP e NVMe)
* S3 Acesso a dados
* Proteção de dados (tecnologias NetApp Snapshot copy, NetApp SnapMirror e SnapVault)
* Eficiências de storage (deduplicação, compactação e compressão)
* Failovers de alta disponibilidade (HA) (incluindo failovers rápidos para SAN de camada 1 com All SAN Array)
* Suporte para configurações de disco all-flash, unidades giratórias e híbridas
* Recursos de segurança (autenticação multifator, criptografia de volume NetApp e limpeza segura)


Esta não é uma lista abrangente; se incluíssemos todos os recursos oferecidos pelo ONTAP, este documento teria centenas de páginas.

Para obter informações mais detalhadas sobre o NetApp ONTAP, consulte a https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf["Folha de dados do software de gerenciamento de dados ONTAP 9"^] e https://docs.netapp.com/ontap-9/index.jsp["documentação do produto"^] a .

link:ontap98fo_simplicity_enhancements.html["Próximo: Melhorias de simplicidade"]
