---
sidebar: sidebar 
permalink: ontap98fo_technical_resources.html 
keywords:  
summary: Esta página contém links para vários recursos técnicos relevantes para o ONTAP 9.8. 
---
= Recursos técnicos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Esta seção abrange os recursos técnicos disponíveis que detalham os recursos mencionados neste documento.



== Relatórios técnicos

* TR-4067: Guia de práticas recomendadas e implementação de NFS da NetApp ONTAP
+
https://www.netapp.com/us/media/tr-4067.pdf["https://www.netapp.com/us/media/tr-4067.pdf"^]

* TR-4375: MetroCluster FC pela ONTAP 9.7
+
https://www.netapp.com/us/media/tr-4375.pdf["https://www.netapp.com/us/media/tr-4375.pdf"^]

* TR-4569: Guia de endurecimento de segurança para ONTAP 9
+
https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf"^]

* TR-4571: Melhores práticas do NetApp FlexGroup volumes
+
https://www.netapp.com/us/media/tr-4571.pdf["https://www.netapp.com/us/media/tr-4571.pdf"^]

* TR-4597: VMware vSphere com ONTAP
+
https://www.netapp.com/us/media/tr-4597.pdf["https://www.netapp.com/us/media/tr-4597.pdf"^]

* TR-4598: Melhores práticas da FabricPool
+
https://www.netapp.com/us/media/tr-4598.pdf["https://www.netapp.com/us/media/tr-4598.pdf"^]

* TR-4678: Proteção de dados e backup - volumes FlexGroup
+
https://www.netapp.com/us/media/tr-4678.pdf["https://www.netapp.com/us/media/tr-4678.pdf"^]

* TR-4689: Arquitetura e design da solução IP da MetroCluster
+
https://www.netapp.com/us/media/tr-4689.pdf["https://www.netapp.com/us/media/tr-4689.pdf"^]

* TR-4705: Arquitetura e Design de soluções da NetApp MetroCluster
+
https://www.netapp.com/pdf.html?item=/media/13480-tr4705pdf.pdf["https://www.netapp.com/pdf.html?item=/media/13480-tr4705pdf.pdf"^]

* TR-4743: FlexCache em ONTAP
+
https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf["https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf"^]





== Podcasts

* Tech OnTap Podcast episódio 263: Virtualização em ONTAP – outono de 2020
+
https://soundcloud.com/techontap_podcast/episode-263-virtualization-in-ontap-fall-2020-update["https://soundcloud.com/techontap_podcast/episode-263-virtualization-in-ontap-fall-2020-update"^]

* Tech OnTap Podcast episódio 264: NetApp ONTAP SnapDiff
+
https://soundcloud.com/techontap_podcast/episode-264-netapp-ontap-snapdiff["https://soundcloud.com/techontap_podcast/episode-264-netapp-ontap-snapdiff"^]

* Tech OnTap Podcast episódio 265: Nuvem NetApp SnapMirror apresentando ProLion
+
https://soundcloud.com/techontap_podcast/episode-265-netapp-snapmirror-cloud-featuring-prolion["https://soundcloud.com/techontap_podcast/episode-265-netapp-snapmirror-cloud-featuring-prolion"^]

* Tech OnTap Podcast episódio 266: Gerenciador de sistemas NetApp ONTAP 9,8
+
https://soundcloud.com/techontap_podcast/episode-266-netapp-system-manager-98["https://soundcloud.com/techontap_podcast/episode-266-netapp-system-manager-98"^]

* Tech OnTap Podcast episódio 267: Continuidade de Negócios SnapMirror
+
https://soundcloud.com/techontap_podcast/episode-267-snapmirror-business-continuity-sm-bc-for-ontap-98["https://soundcloud.com/techontap_podcast/episode-267-snapmirror-business-continuity-sm-bc-for-ontap-98"^]


